name: CI/CD
run-name: ${{ github.actor }} is testing CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      HARMOGESTION_DB_USERNAME: ${{ secrets.DB_USERNAME }}
      HARMOGESTION_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      HARMOGESTION_DB_HOST: ${{ secrets.DB_HOST }}
      HARMOGESTION_DB_PORT: ${{ secrets.DB_PORT }}
      HARMOGESTION_API_PORT: ${{ secrets.API_PORT }}
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: wait_for_MySQL_to_be_ready
        run: |
          while ! mysqladmin ping -h"${{ secrets.DB_HOST }}" -P"${{ secrets.DB_PORT }}" --silent; do
            sleep 1
          done
      - name: Create DB from script
        run: mysql --host ${{ secrets.DB_HOST }} --port ${{ secrets.DB_PORT }} -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} < scripts/ScriptCreationBDD.sql
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarQube packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ThomasSeiwert_HarmoGestion_API
      - name: Charging artefact
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: target/*.jar
          retention-days: 1